language: c
dist: trusty
sudo: required
env:
 - AGDATA=`pwd`/data PGPORT=61958

before_script:
 - ./configure --prefix="$(pwd)"
 - export PATH="$(pwd)"/bin:$PATH
 - make install-world > /dev/null
 - initdb
 - pg_ctl start -w

script: make installcheck
